spring.application.name=application
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:16847/railway
spring.datasource.username=root
spring.datasource.password=mfKYrzdpQZmaiEVafOhCOcKblBuPrmDw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#spring.application.name=application
#server.port=9090
#spring.profiles.active=local
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true