#spring.application.name=application
#server.port=${PORT:8080}
#
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=2525
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#
#mail.from=${MAIL_FROM}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#spring.mail.properties.mail.smtp.connectiontimeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.writetimeout=10000
#
#spring.mail.properties.mail.debug=true
#spring.profiles.active=local


spring.application.name=application

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

brevo.api.key=${BREVO_API_KEY}
mail.from=${MAIL_FROM}